version: "3"
services:
  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    volumes:
      - data:/var/lib/postgresql/data/

volumes:
  data:
